### ISSUE TITLE
Using a different feature extractor

### ISSUE THREAD

**Issue by jianboma** [hbredin/TristouNet#1]
Hi,
I'm implementing this code. As I have my own features, I try to modify the generator to accommodate my own features. But got error when feed into training. The network structure are the same.

The outcome of next(my_generator) is a tuple and has two elements. First element consists of 3 sequences (dimension of each is (200,39)). The second element is {int} 1. The error comes when I start the code
`# actual training`
`embedding.fit(input_shape, my_generator, samples_per_epoch, nb_epoch)`

And the error is 

> Exception: Error when checking model target: data should be a Numpy array, or list/dict of Numpy arrays. Found: 1...

I realize it may because of {int} 1 in my_generator. I modified the generator as

`target_num = list(np.array([1]))`
`yield [sequences[anchor], sequences[positive], sequences[negative]], target_num`

But another error comes like
> IndexError: tuple index out of range

I think it should be caused by my_generator. Is the outcome of next(my_generator) right for the network training.

Any comments will be appreciated. Thanks.

**Comment by hbredin** [comment]
Before going any further, do you confirm that the provided code (before your changes) is working?

If so, then I guess you need to tell me a bit more about your changes. 
A diff between my and your version would be useful :) 

I need to be able to reproduce the error locally -- otherwise I cannot help you.

**Comment by jianboma** [comment]
Thanks for your reply.

I don't have access to database which you used. That's why it's hard for me to check whether codes you provided works or not on my machine. I think it will be pretty useful if you provide several wave files and protocol in case someone don't have access to database. Not sure whether I'm right :)

In terms of what I have changed, I uploaded the script I wrote. Basically, I load mfcc features according to a list and form them into triplets. Could you have a look at my code and have a guess what caused the problem if time is permitted for you. 
Thanks.
[train_my_generator.txt](https://github.com/hbredin/TristouNet/files/866643/train_my_generator.txt)
[features_list_file.txt](https://github.com/hbredin/TristouNet/files/866644/features_list_file.txt)

**Comment by hbredin** [comment]
> I don't have access to database which you used. That's why it's hard for me to check whether codes you provided works or not on my machine.

As stated in the README file, you can easily modify the github.com/pyannote/pyannote.db.etape package to match your own database. I am even willing to help (if this database is public).

> I think it will be pretty useful if you provide several wave files and protocol in case someone don't have access to database. Not sure whether I'm right :)

The ETAPE database can be obtained easily from ELRA (see README file) and it is not that expensive for academic research.
If you are aware of a completely open, free, and public database with "who speaks when" annotations, please let me know.

> In terms of what I have changed, I uploaded the script I wrote. Basically, I load mfcc features according to a list and form them into triplets. Could you have a look at my code and have a guess what caused the problem if time is permitted for you.

.fit() expects batches of triplets, not just triplets.
This might be the cause of your problem.

((anchors, positives, negatives), fake_labels)

anchors, positives, negatives : batch_size x n_samples x n_features numpy arrays 
fake_labels : batch_size (or batch_size x 1) numpy array

**Comment by jianboma** [comment]
Hi Hervé,

I changed the input as batches of triplets. It works. Thanks for your kind help.
