### ISSUE TITLE
about the ETAPE corpus

### ISSUE THREAD

**Issue by NemoCpp** [hbredin/TristouNet#3]
hi Hervé BREDIN,
I'd like to try your code, but I've no ETAPE corpus. And I want to try it on CallHome(talkbank) corpus, Could you  tell me how to "adapt the code to such database"

**Comment by hbredin** [comment]
This repository has been deprecated in favor of [pyannote.audio](https://github.com/pyannote/pyannote-audio).

If you read the [tutorial](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/speaker-embedding#neural-speech-turn-embedding-with-pyannoteaudio) carefully, there are indications on how to create [your own interface](https://github.com/pyannote/pyannote-db-template#pyannotedatabase-plugin) to your own corpus. 

For instance, someone [contributed](https://github.com/ironiksk/pyannote-db-librispeech) their own Librispeech plugin. If you do the same for Callhome, I'd love to integrate your pyannote-db-callhome plugin to the pyannote suite. Keep me posted!
 
I am closing this issue. Please open an issue in [pyannote-db-template](https://github.com/pyannote/pyannote-db-template) if you encounter problems when designing your own pyannote-db-callhome plugin.
