### ISSUE TITLE
Should silence removal precede Triplet Generation ?

### ISSUE THREAD

**Issue by aniket03** [hbredin/TristouNet#4]
In the triplet generation phase. Do we need to pre-process the audio to remove silent phases, in order to achieve a better quality of triplets? Further IMO silence removal might have a greater impact on shorter duration audio segments like 500 ms than longer ones [2s].

Do you think silence removal thus should be part of the overall pipeline? Or does TristouNet inherently robust to silence blocks and doesn't require removing them.

**Comment by hbredin** [comment]
I agree with all your suggestions.

TristouNet is designed to work on pure speech segments (i.e. one speaker, no silence) and was only trained on this kind of segments.

That being said, one could try to add an attention mechanism to automatically infer that silence regions should be down-weighed.

Note: this repo is no longer maintained. Please use [pyannote-audio](https://github.com/pyannote/pyannote-audio) instead. Closing.

**Comment by aniket03** [comment]
Sure thanks!
